name: anchore-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchore-analysis:
    uses: paniclobster/github-workflows/.github/workflows/docker-anchore-analysis.yaml@main
    with:
      docker_image_name: paniclobster/node-puppeteer
