name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: paniclobster/github-workflows/.github/workflows/docker-build.yaml@main
    with:
      docker_image_name: paniclobster/node-puppeteer
