name: build-publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-publish:
    uses: paniclobster/github-workflows/.github/workflows/docker-build-publish.yaml@main
    with:
      docker_image_name: public.ecr.aws/paniclobster/node-puppeteer
    secrets:
      docker_login_registry: public.ecr.aws
      docker_login_username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
      docker_login_password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
